export const AREAS_COMUNES = [
  'Dirección',
  'Gerencia',
  'Administración',
  'Ventas',
  'Marketing',
  'Comercial',
  'Atención al Cliente',
  'Soporte',
  'Sistemas',
  'TI',
  'Desarrollo',
  'Infraestructura',
  'Finanzas',
  'Contabilidad',
  'Tesorería',
  'RRHH',
  'Legal',
  'Compras',
  'Logística',
  'Operaciones',
  'Producción',
  'Calidad',
  'Auditoría',
  'Planeamiento',
  'Proyectos',
  'PMO',
  'Seguridad',
  'Mantenimiento'
]

